# Generated by Django 5.1.4 on 2025-01-01 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_1_name', models.CharField(max_length=255)),
                ('parent_1_phone', models.CharField(max_length=20)),
                ('parent_1_email', models.EmailField(max_length=254)),
                ('parent_2_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_2_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_2_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('payment_preferences', models.CharField(choices=[('EFT', 'EFT'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Direct Payment', 'Direct Payment')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('allergy_info', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.family')),
            ],
        ),
    ]
