# Generated by Django 5.1.4 on 2025-01-01 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('government_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(choices=[('EFT', 'EFT'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Direct Payment', 'Direct Payment')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.family')),
            ],
        ),
    ]
