# Generated by Django 5.1.4 on 2025-01-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_payment_government_contribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_source', models.CharField(max_length=255)),
                ('stream', models.CharField(max_length=255)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
