# Generated by Django 5.1.4 on 2025-01-02 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_governmentfunding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='capacity',
        ),
        migrations.AddField(
            model_name='classroom',
            name='max_capacity',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='program_type',
            field=models.CharField(choices=[('Infant', 'Infant'), ('Toddler', 'Toddler'), ('Preschool', 'Preschool')], default='Infant', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AlternativeCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('Infant', 'Infant'), ('Toddler', 'Toddler'), ('Preschool', 'Preschool')], max_length=50)),
                ('max_capacity', models.PositiveIntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_capacities', to='core.classroom')),
            ],
        ),
    ]
