# Generated by Django 5.1.4 on 2025-01-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_classroom_capacity_classroom_max_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='classroom_name',
        ),
    ]
