# Generated by Django 5.1.4 on 2025-01-04 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_alternativecapacity_max_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',        ),
        migrations.AddField(
            model_name='invoice',
            name='full_tuition',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
    	    model_name='invoice',
    	    name='invoice_id',
    	    field=models.AutoField(primary_key=True),  # AutoField generates IDs automatically
	),
        migrations.AddField(
            model_name='invoice',
            name='parent_portion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.child'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
