# Generated by Django 5.1.4 on 2025-01-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_type', models.CharField(choices=[('Security', 'Security'), ('FOB', 'FOB')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Owing', 'Owing'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Forfeited', 'Forfeited')], default='Owing', max_length=20)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('date_refunded', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.child')),
            ],
        ),
    ]
