# Generated by Django 5.1.4 on 2025-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='parent_portion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subsidy_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
