# Generated by Django 5.1.4 on 2025-01-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_invoice_due_amount_alter_invoice_date_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_weekday', models.BooleanField(default=True)),
                ('is_stat_holiday', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
    ]
