# Generated by Django 5.1.4 on 2025-01-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='stat_substitution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
