# Generated by Django 5.1.4 on 2025-01-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_calendar_stat_substitution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(max_length=50)),
                ('daily_tuition_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('parent_daily_cap', models.DecimalField(decimal_places=2, max_digits=6)),
                ('government_daily_subsidy', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
