# Generated by Django 5.1.4 on 2025-01-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subsidyrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='end_date',
            new_name='enrollment_end_date',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='start_date',
            new_name='enrollment_start_date',
        ),
        migrations.RemoveField(
            model_name='child',
            name='name',
        ),
        migrations.AddField(
            model_name='child',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='fob_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
