# Generated by Django 5.1.4 on 2025-01-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_end_date_child_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidyrate',
            old_name='government_daily_subsidy',
            new_name='daily_CWELCCA_rate',
        ),
        migrations.RenameField(
            model_name='subsidyrate',
            old_name='parent_daily_cap',
            new_name='daily_parent_rate',
        ),
    ]
