# Generated by Django 5.1.4 on 2025-01-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_government_daily_subsidy_subsidyrate_daily_cwelcca_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_id',
            new_name='id',
        ),
    ]
