# Generated by Django 5.1.4 on 2025-01-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_invoice_id_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_id',
        ),
        migrations.AddField(
    model_name='deposit',
    name='id',
    field=models.BigAutoField(
        auto_created=True,
        primary_key=True,
        serialize=False,
        verbose_name='ID'
    ),
    preserve_default=False,
)

    ]
