# Generated by Django 5.1.4 on 2025-01-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_deposit_deposit_id_deposit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='emergency_contact',
        ),
    ]
