# Generated by Django 5.1.4 on 2025-01-08 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_transition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('withdrawal_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_reason', models.TextField()),
                ('status', models.CharField(choices=[('refunded', 'Refunded'), ('forfeited', 'Forfeited'), ('held', 'Held')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
