# Generated by Django 5.1.4 on 2025-01-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='max_capacity',
        ),
    ]
