# Generated by Django 5.1.4 on 2025-01-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_attendance_max_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='enrolled_children',
        ),
    ]
