# Generated by Django 5.1.4 on 2025-01-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_attendance_enrolled_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
