# Generated by Django 5.1.4 on 2025-01-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_transition_processed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(condition=models.Q(('processed', False)), fields=('child',), name='unique_unprocessed_transition'),
        ),
    ]
