# Generated by Django 5.1.4 on 2025-01-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_transition_unique_unprocessed_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='is_weekday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='core.child'),
        ),
    ]
